// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkJBRH7n8kIOxV8qFAr9Ih8FC2QZYUMOo',
    appId: '1:61941468117:web:73b3d25f03d63124a1cb5c',
    messagingSenderId: '61941468117',
    projectId: 'todotask-1c382',
    authDomain: 'todotask-1c382.firebaseapp.com',
    storageBucket: 'todotask-1c382.firebasestorage.app',
    measurementId: 'G-YBM72HSPHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASIHMISsvBb2dV-twa-9_3argWdPOjtfw',
    appId: '1:61941468117:android:5a12e101d1b7eeb1a1cb5c',
    messagingSenderId: '61941468117',
    projectId: 'todotask-1c382',
    storageBucket: 'todotask-1c382.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYUVF42gRr5jCeYJ7fgNhbsh0nRoloIeQ',
    appId: '1:61941468117:ios:50b7c5a11bc665a1a1cb5c',
    messagingSenderId: '61941468117',
    projectId: 'todotask-1c382',
    storageBucket: 'todotask-1c382.firebasestorage.app',
    iosBundleId: 'com.example.todotask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYUVF42gRr5jCeYJ7fgNhbsh0nRoloIeQ',
    appId: '1:61941468117:ios:50b7c5a11bc665a1a1cb5c',
    messagingSenderId: '61941468117',
    projectId: 'todotask-1c382',
    storageBucket: 'todotask-1c382.firebasestorage.app',
    iosBundleId: 'com.example.todotask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkJBRH7n8kIOxV8qFAr9Ih8FC2QZYUMOo',
    appId: '1:61941468117:web:dbd71d3682f681c3a1cb5c',
    messagingSenderId: '61941468117',
    projectId: 'todotask-1c382',
    authDomain: 'todotask-1c382.firebaseapp.com',
    storageBucket: 'todotask-1c382.firebasestorage.app',
    measurementId: 'G-VB98F3N49J',
  );
}
